name: Deploy a watify.mx

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Construir app
        run: npm run build && echo "$(date -u)" > dist/version.txt

      - name: Deploy frontend → public_html/app/
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.FTPUSER }}
          password: ${{ secrets.FTPPASSWORD }}
          local-dir: ./dist/
          server-dir: ./app/
          protocol: ftp
          dangerous-clean-slate: true
          log-level: verbose

      - name: Deploy API PHP → public_html/api/
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.FTPUSER }}
          password: ${{ secrets.FTPPASSWORD }}
          local-dir: ./api/
          server-dir: ./api/
          protocol: ftp
          exclude: |
            **/.git*
            **/config/db.php
